Homework 1
bigseized/TinkoffCourseJava2023 pull request #2
Opened 2023-10-09 22:22 UTC by bigseized

2023-10-12 19:57 UTC, SHvatov requested changes
@bigseized оставил комментики + в тестах вижу много позитвиных тестов, но очень мало негативных (со всякими некорректными данными и тп). Давай добавим их?

2023-10-12 19:57 UTC, SHvatov commented on src/main/java/edu/hw1/task1/VideoDuration.java
> +            minutes = Integer.parseInt(splitedString[0]);
Лучше сначала провалидировать входную строку, после чего уже парсить числа из строки - работа с исключениями (а именно их порождение), штука достаточно дорогостоящая (https://www.baeldung.com/java-exceptions-performance, https://stackoverflow.com/questions/299068/what-are-the-effects-of-exceptions-on-performance-in-java), поэтому желательно кидать и перехватывать их только при надобности.

2023-10-12 19:57 UTC, SHvatov commented on src/main/java/edu/hw1/task1/VideoDuration.java
> +        } else {
можно без else ветки

2023-10-12 19:57 UTC, SHvatov commented on src/main/java/edu/hw1/task3/NestableArray.java
> +        for (int j : firstArray) {
Классно, что в данной задаче попробовал работу с итерированием по коллекции с помощью различных вариаций for-цикла, однако видно, что код дублируется. Давай вынесем поиск мин/макса в отдельный метод?

2023-10-12 19:57 UTC, SHvatov commented on src/main/java/edu/hw1/task5/Palindrome.java
> +    final static int DEC = 10;
`private`, в противном случае почем зря загрязняем пространство имен

2023-10-12 19:57 UTC, SHvatov commented on src/main/java/edu/hw1/task5/Palindrome.java
> +            int firstDigit = Integer.parseInt(String.valueOf(numberInStringFormat.charAt(i)));
`numberInStringFormat.charAt(i) - 48;` - чтобы не делать лишние конвертации и парсинг

2023-10-12 19:57 UTC, SHvatov commented on src/main/java/edu/hw1/task1/VideoDuration.java
> +    static int minutesToSeconds(String input) {
1. Лучше сделать public, все-таки метод около-библиотечный у нас. 
2. Знаю, что в задании метод так называется, но вообще лучше, чтобы в его названии был глагол, к примеру `convert...`. В большинстве случае метод = действие, очень редко методы-геттеры называют в fluent-стиле по названию поля.

2023-10-12 19:57 UTC, SHvatov commented on src/main/java/edu/hw1/task6/KaprekarsConstant.java
> +    private static Character[] typecastCharArrToWrappedCharArr(char[] charArray) {
1. приватные методы лучше держать внизу, в большинстве людей интересует публичный интерфейс класса
2. [Reading code from Top to Bottom: The Stepdown Rule](https://ashishmd.medium.com/summary-of-clean-code-by-robert-c-martin-part-3-functions-72b3115472e)

2023-10-12 19:57 UTC, SHvatov commented on src/main/java/edu/hw1/task6/KaprekarsConstant.java
> +    final static int KAPREKARS_CONST = 6174;
`private`

2023-10-12 19:57 UTC, SHvatov commented on src/main/java/edu/hw1/task6/KaprekarsConstant.java
> +
лишняя пустая строка

2023-10-12 19:57 UTC, SHvatov commented on src/main/java/edu/hw1/task6/KaprekarsConstant.java
> +        while (true) {
1. Нужна валидация, я могу передать любое число и словить бесконечный цикл
2. Надо добавить тестов по разным классам эквивалентности данных
3. На будущее - в продуктовом коде бесконечные циклы почти никогда не встречаются. Если алгоритм того требует, то мы явно накладываем ограничение на кол-во итераций, чтобы в случае ошибки не зависнуть, а отвалиться с человеко-читаемой ошибкой и пойти работать дальше. К примеру, в данном случае мы знаем, что алгоритм требует максимум 7 шагов. Значит, если кол-во итераций больше 7, то что-то пошло не так и можно кинуть ошибку. То же правило применимо к рекурсиям.

2023-10-12 19:57 UTC, SHvatov commented on src/main/java/edu/hw1/task7/BitShift.java
> +        char buffer = '-';
'-' лучше вынести в константу

2023-10-12 19:57 UTC, SHvatov commented on src/main/java/edu/hw1/task8/BoardCapture.java
> +                int[][] possibleMoves = {
тоже лучше вынести в константу, чем на каждый вызов создавать по новому массиву

2023-10-12 19:57 UTC, SHvatov commented on src/test/java/edu/hw1/task3/NestableArrayTest.java
> +    @DisplayName("isNestable([1, 2, 3, 4], [0, 6]) -> true")
https://www.baeldung.com/parameterized-tests-junit-5#6-method - вот тут можно почитать про параметризацию тестов со сложными аргументами

2023-10-12 19:57 UTC, SHvatov commented on src/test/java/edu/hw1/task8/BoardCaptureTest.java
> +    @DisplayName("Test 1 -> true")
DisplayName все-таки должен передавать суть теста, чтобы если что, можно было, к примеру, из отчета в аллюре понять, про что он и что потенциально могло отвалиться

2023-10-13 18:10 UTC, bigseized commented on src/main/java/edu/hw1/task1/VideoDuration.java
> +        } else {
+

2023-10-13 18:57 UTC, bigseized commented on src/main/java/edu/hw1/task1/VideoDuration.java
> +            minutes = Integer.parseInt(splitedString[0]);
готово

2023-10-13 19:07 UTC, bigseized commented on src/main/java/edu/hw1/task1/VideoDuration.java
> +    static int minutesToSeconds(String input) {
готово

2023-10-13 21:15 UTC, bigseized commented on src/main/java/edu/hw1/task5/Palindrome.java
> +    final static int DEC = 10;
готово

2023-10-13 21:28 UTC, bigseized commented on src/main/java/edu/hw1/task3/NestableArray.java
> +        for (int j : firstArray) {
готово

2023-10-13 21:28 UTC, bigseized commented on src/main/java/edu/hw1/task5/Palindrome.java
> +            int firstDigit = Integer.parseInt(String.valueOf(numberInStringFormat.charAt(i)));
готово

2023-10-13 21:30 UTC, bigseized commented on src/main/java/edu/hw1/task6/KaprekarsConstant.java
> +    final static int KAPREKARS_CONST = 6174;
готово

2023-10-13 21:32 UTC, bigseized commented on src/main/java/edu/hw1/task6/KaprekarsConstant.java
> +    private static Character[] typecastCharArrToWrappedCharArr(char[] charArray) {
готово

2023-10-13 21:34 UTC, bigseized commented on src/main/java/edu/hw1/task6/KaprekarsConstant.java
> +
готово

2023-10-14 00:16 UTC, bigseized commented on src/main/java/edu/hw1/task6/KaprekarsConstant.java
> +        while (true) {
готово

2023-10-14 00:18 UTC, bigseized commented on src/main/java/edu/hw1/task7/BitShift.java
> +        char buffer = '-';
готово

2023-10-14 00:28 UTC, bigseized commented on src/main/java/edu/hw1/task8/BoardCapture.java
> +                int[][] possibleMoves = {
готово

2023-10-14 01:00 UTC, bigseized commented on src/test/java/edu/hw1/task8/BoardCaptureTest.java
> +    @DisplayName("Test 1 -> true")
готово

2023-10-14 02:08 UTC, bigseized commented on src/test/java/edu/hw1/task3/NestableArrayTest.java
> +    @DisplayName("isNestable([1, 2, 3, 4], [0, 6]) -> true")
готово

2023-10-15 09:46 UTC, SHvatov requested changes
@bigseized оставил пару минорных комментариев, ДЗ аппрувну сейчас, а МР уже после их правки.

2023-10-15 09:46 UTC, SHvatov commented on src/main/java/edu/hw1/task1/VideoDuration.java
> +        int minutes;
1. Вместо того чтобы отделять инициализацию от определения, лучше просто инвертировать if, возвращая -1, если строка не валидная, и продолжаю работу метода и объявляя нужные переменные
2. Я бы проверку вынес в отдельный метод, а `notNegativeNumberRegex` скомпилировал в паттерн, унес бы в статик и использовал его, а то этот процесс достаточно ресурсозатратный.

2023-10-15 09:46 UTC, SHvatov commented on src/main/java/edu/hw1/task4/BrokenString.java
> +        String fixedString = "";
лучше через `StringBuilder`

2023-10-15 09:46 UTC, SHvatov commented on src/main/java/edu/hw1/task6/KaprekarsConstant.java
> +    private static boolean checkIsAllDigitsEqual(int number) {
`areAllDigitsEqual`. Булевые методы дают ответ на задаваемый вопрос, поэтому и имеют в названии вопросительную форму - `isValid, isApplicable, isKnightPresent. etc`

2023-10-15 09:46 UTC, SHvatov commented on src/main/java/edu/hw1/task8/BoardCapture.java
> +    @SuppressWarnings("checkstyle:MagicNumber") public static boolean knightBoardCapture(int[][] knightPlacement) {
Аннотации над методом

2023-10-15 09:46 UTC, SHvatov commented on src/main/java/edu/hw1/task8/BoardCapture.java
> +                    if (newX >= 0 && newX < size && newY >= 0 && newY < size && knightPlacement[newX][newY] == 1) {
Я бы все со строки 29 до строки 38 вынес в метод

2023-10-15 09:50 UTC, SHvatov commented on src/main/java/edu/hw1/task6/KaprekarsConstant.java
> +        String arrInStringFormat = "";
Тут тоже лучше через SB

2023-10-15 12:55 UTC, merged