Project 2
bigseized/TinkoffCourseJava2023 pull request #7
Opened 2023-11-05 13:40 UTC by bigseized

2023-11-12 15:19 UTC, SHvatov requested changes
@bigseized оставил пару комментариев, посмотри их, пожалуйста.

2023-11-12 15:19 UTC, SHvatov commented on pom.xml
> +            <groupId>org.projectlombok</groupId>
🔥

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/MazeSolver.java
> +    private final static Logger LOGGER = Logger.getLogger(MazeSolver.class.getName());
У ломбока есть классная аннотация @Log4j - https://projectlombok.org/features/log

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/MazeSolver.java
> +    private final Scanner in = new Scanner(System.in);
Можно тоже статиком сделать, или же унести чуть пониже, чтобы не затерялось среди статических констант.

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/MazeSolver.java
> +        Integer generationVariant = getChooseInput();
`getChooseInput` -> `getMazeGenerationAlgorithmChoice`

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/MazeSolver.java
> +        Maze maze = mazeCreate(mazeSize, generationVariant);
`createMaze`

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/MazeSolver.java
> +        Integer generationVariant = getChooseInput();
А, `getChooseInput` отвечает за выбор одного из двух вариантов. Может, тогда `getChoiceInput`, `Choose` - глагол)

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/MazeSolver.java
> +                LOGGER.info("Необходимо ввести 2 числа!");
Я бы сделал логи уровня `ERROR`, аналогично в других местах.

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/MazeSolver.java
> +        while (isCoordinatesCorrect(startCoordinate, grid));
В классическом варианте для жабы while на той же строке, что и закрывающая скобочка

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/MazeSolver.java
> +        while (isCoordinatesCorrect(startCoordinate, grid));
И выбор пары координат дублируется, можно в метод

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/MazeSolver.java
> +    private boolean isCoordinatesCorrect(Coordinate coordinate, Cell[][] grid) {
is -> are, координаты же

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/MazeSolver.java
> +    private Maze mazeCreate(Pair<Integer, Integer> size, Integer genVariant) {
Выбор алгоритма для создания солвера и генератора я бы вынес в отдельные сущности ([Паттерн приспособленец](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D1%81%D0%BF%D0%BE%D1%81%D0%BE%D0%B1%D0%BB%D0%B5%D0%BD%D0%B5%D1%86_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)))

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/MazeSolver.java
> +    private List<Coordinate> mazeSolve(
`solveMaze`, чтобы на английском звучало хорошо. А то представь, у тебя два метода - `найтиВыходВЛабиринте` или `лабиринтВыходНаходить`. Какой нейминг тебе больше нравится?)

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/drawers/ConsoleDrawer.java
> +        Cell[][] copyGrid = ArraysUtils.copyDeepCellArr(grid);
А зачем копировать сетку?

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/drawers/Drawer.java
> +    void draw(Cell[][] maze, List<Coordinate> path);
Я бы метод назвал немного по-другому, все-таки тут мы не просто рисуем лабиринт, но еще и путь в нем.

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/generators/DFSAlgorithmGenerator.java
> +    private ArrayList<Pair<Integer, Integer>> getAvailableShifts(
На будущее - лучше указывать по возможности интерфейс, а не конкретную его реализацию. 
- https://stackoverflow.com/questions/2279030/type-list-vs-type-arraylist-in-java
- https://stackoverflow.com/questions/383947/what-does-it-mean-to-program-to-an-interface

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/generators/DFSAlgorithmGenerator.java
> +    private ArrayList<Pair<Integer, Integer>> getAvailableShifts(
Аналогично и на 84 строке.

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/generators/PrimsAlgorithmGenerator.java
> +                    case NORTH -> {
Кейсы бы я вынес в отдельные методы. ИМХО, кейс больше одной строки плохо читается и имеет тенденцию потом разрастаться и, в итоге, деградировать)

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/solvers/BFSAlgorithmSolver.java
> +            if (p.getCol() + 1 < grid.length
Таких длинных, мало что говорящих постороннему читателю условий стоит избегать. Лучше вынести условие в if'e в отдельный метод с говорящим названием.

2023-11-12 15:19 UTC, SHvatov commented on src/main/java/edu/project2/solvers/DFSAlgorithmSolver.java
> +            if (newRow >= 0 && newRow < grid.length && newCol >= 0 && newCol < grid[0].length
Вот это условие удьтра хард понять)

2023-11-14 14:38 UTC, bigseized commented on src/main/java/edu/project2/drawers/ConsoleDrawer.java
> +        Cell[][] copyGrid = ArraysUtils.copyDeepCellArr(grid);
В этом месте действительно незачем, а в целом нужно было в некоторых методах менять сетку чтобы изменения не сказались на другой логике.

2023-11-14 23:11 UTC, bigseized commented on src/main/java/edu/project2/generators/PrimsAlgorithmGenerator.java
> +                    case NORTH -> {
Переписал по аналогии с генерацией с помощью поиска в глубину.

2023-11-14 23:24 UTC, bigseized commented on src/main/java/edu/project2/solvers/BFSAlgorithmSolver.java
> +            if (p.getCol() + 1 < grid.length
Тоже решил переписать используя SHIFTS

2023-11-14 23:46 UTC, bigseized commented on src/main/java/edu/project2/solvers/DFSAlgorithmSolver.java
> +            if (newRow >= 0 && newRow < grid.length && newCol >= 0 && newCol < grid[0].length
переписал это и аналогичные условия в других классах

2023-11-15 00:07 UTC, bigseized commented on src/main/java/edu/project2/MazeSolver.java
> +    private final static Logger LOGGER = Logger.getLogger(MazeSolver.class.getName());
Решил для этого проекта использовать аннотацию @Log чтобы не переписывать тесты)

2023-11-15 00:08 UTC, bigseized commented on src/main/java/edu/project2/MazeSolver.java
> +                LOGGER.info("Необходимо ввести 2 числа!");
Сделал аналогичный уровень SEVERE.

2023-11-17 06:48 UTC, SHvatov approved these changes
@bigseized 👍, можно мержить)

2023-11-17 18:14 UTC, merged