Homework 5
bigseized/TinkoffCourseJava2023 pull request #8
Opened 2023-11-12 00:58 UTC by bigseized

2023-11-14 20:49 UTC, SHvatov requested changes
@bigseized оставил пару мелких комментов. Посмотри их, пожалуйста.

2023-11-14 20:49 UTC, SHvatov commented on src/main/java/edu/hw5/task1/ClubAnalytics.java
> +        long sumOfTimes = 0L;
ИМХО, `totalSeconds` было бы более говорящим названием

2023-11-14 20:49 UTC, SHvatov commented on src/main/java/edu/hw5/task1/ClubAnalytics.java
> +        return ldt.getHour() + "ч " + ldt.getMinute() + "м";
На будущее - https://www.baeldung.com/java-ms-to-hhmmss. Спойлер - у апаче есть утильный класс на любой чих.

2023-11-14 20:49 UTC, SHvatov commented on src/main/java/edu/hw5/task2/FridayThe13th.java
> +        ArrayList<String> fridays = new ArrayList<>();
Лучше указывать по возможности интерфейс, а не конкретную его реализацию. 
- https://stackoverflow.com/questions/2279030/type-list-vs-type-arraylist-in-java
- https://stackoverflow.com/questions/383947/what-does-it-mean-to-program-to-an-interface

Там про всякие принципы Лисков, да и если придется поменять реализацию, сделать это будет гораздо проще.

2023-11-14 20:49 UTC, SHvatov commented on src/main/java/edu/hw5/task2/FridayThe13th.java
> +        return fridays.toString();
Лучше вернуть лист, а не строку - универсальнее будет.

2023-11-14 20:49 UTC, SHvatov commented on src/main/java/edu/hw5/task2/FridayThe13th.java
> +        while (true) {
В продакшен-коде таких бесконечных циклов лучше изебгать.

2023-11-14 20:49 UTC, SHvatov commented on src/main/java/edu/hw5/task3/AbstractDateParser.java
> +    abstract Optional<LocalDate> parse(String date);
`public`?

2023-11-14 20:49 UTC, SHvatov commented on src/main/java/edu/hw5/task3/DashDelimiterTwoDigitsParser.java
> +public class DashDelimiterTwoDigitsParser extends AbstractDateParser {
Идентичен первому, можно вынести в общий абстрактный класс, в который просто передавать паттерн.

2023-11-14 20:49 UTC, SHvatov commented on src/main/java/edu/hw5/task4/PasswordCheck.java
> +    private PasswordCheck() {
Кстати, я так понял, что вам ломбок уже показали? Можно его потихоньку в проекты интегрировать.

2023-11-15 01:04 UTC, bigseized commented on src/main/java/edu/hw5/task4/PasswordCheck.java
> +    private PasswordCheck() {
На семинаре рассмотрели несколько полезных аннотаций, отдельной темы в лекциях ещё не было.

2023-11-15 12:56 UTC, bigseized commented on src/main/java/edu/hw5/task3/DashDelimiterTwoDigitsParser.java
> +public class DashDelimiterTwoDigitsParser extends AbstractDateParser {
Не уверен, что правильно понял, но попробовал переписать, используя общий абстрактный класс.

2023-11-17 06:44 UTC, SHvatov commented on src/main/java/edu/hw5/task4/PasswordCheck.java
> +    private PasswordCheck() {
В лекциях, ЕМНИП, и не будет) Но использовать потихоньку уже можно - позволит избавиться от bolierplate кода.

2023-11-17 06:44 UTC, SHvatov approved these changes
@bigseized 👍 можно мержить

2023-11-17 18:08 UTC, merged